pipeline {
    agent any

    tools {
        maven 'M3'
        jdk 'JDK-17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/Shahabuddin999/All_Projects.git'
            }
        }

        stage('Build') {
            steps {
                dir('jenkinDemo') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Run App & Test API') {
            steps {
                dir('jenkinDemo') {
                    // Start the app in background
                    bat 'start /B java -jar target\\jenkinDemo-0.0.1-SNAPSHOT.jar'
                    
                    // Wait a few seconds for app to start
                    bat 'ping -n 10 127.0.0.1 > nul'

                    // Hit API endpoint
                    bat 'curl http://localhost:8080/show'

                    // Stop Java process after test
                    bat 'taskkill /F /IM java.exe'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying application..."
            }
        }
    }

    post {
        success {
            echo "✅ Build and API test successful!"
        }
        failure {
            echo "❌ Build or test failed!"
        }
    }
}
