pipeline {
    agent any

    tools {
        maven 'M3'
        jdk 'JDK-17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-creds', url: 'https://github.com/Shahabuddin999/All_Projects.git'
            }
        }

        stage('Build') {
            steps {
                dir('jenkinDemo') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('jenkinDemo') {
                    bat 'mvn test'
                }
            }
        }

        stage('Deploy & Test API') {
            steps {
                dir('jenkinDemo') {
            echo "🚀 Starting application on port 8081..."
            bat 'for /f "tokens=5" %a in (\'netstat -ano ^| findstr :8081\') do taskkill /F /PID %a'
            bat 'start /MIN java -jar target\\jenkinDemo-0.0.1-SNAPSHOT.jar'
        }
            }
        }
    }

    post {
        success {
            echo "✅ Build, deployment & API test successful!"
        }
        failure {
            echo "❌ Build or API test failed!"
        }
    }
}
