spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 785483ef91b33d1e9fe0
            client-secret: fe8504c3925b4171aa8105eb8309b8b33d5d16a8
          google:
            client-id: 256126201412-j73vgke1k82ocpae79hkukeisuimkh4c.apps.googleusercontent.com
            client-secret: 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
        
