spring:
  application:
    name: Kafka_With_Manual_Commit

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      enable-auto-commit: false   # manual commit
      auto-offset-reset: earliest

