apiVersion: v1                            # API version for Service object
kind: Service                             # Kubernetes object type: Service
metadata:
  name: kubernate-using-yml-file-service  # Name of the Service
  labels:
    app: kubernate-using-yml-file         # Labels to identify the Service
spec:
  type: NodePort                          # Exposes the service on a static port on each Node’s IP
  selector:
    app: kubernate-using-yml-file         # Selects Pods with this label to route traffic to
  ports:
    - port: 8080                          # Port exposed by the Service inside the cluster
      targetPort: 8080                    # Port the container is listening on
      nodePort: 30036                     # Port exposed externally on the Node (accessible outside the cluster)
