version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: shahabuddin
    ports:
      - "5432:5432"
    networks:
      - springboot-network

  app:
    build: .  
    image: bootwithdatabase
    container_name: springboot-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shahabuddin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecret
    command: sh -c "sleep 10 && java -jar app.jar"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
